### ISSUE TITLE
menu pricipal, desplegable, creación de partidas y salas

### ISSUE THREAD

**Issue by Acheregido** [UNIZAR-30226-2023-02/Front-Web#3]
hacer las pantallas funcionales de menu principal del juego, con el desplegable integrado y la realización de la creación de partidas, junto con las salas de juego

**Comment by Acheregido** [comment]
Pantallas de menú de juego y de crear partida terminadas, con desplegable incluido

**Comment by Rober-Garcia** [comment]
pantalla de creación de la partida en modo clasico realizado y pantalla de esperando jugadores realizada

**Comment by Rober-Garcia** [comment]
solo falta la comunicación con el backend
